name: Deploy build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: self-hosted
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        EC2_INSTANCE_IP: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        EC2_PASSWORD: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore mvc-app.sln

    - name: Build Solution
      run: |
        msbuild.exe mvc-app.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
    
    #- name: Download PuTTY Installer
    #  run: |
    #    Invoke-WebRequest -Uri 'https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.79-installer.msi' -OutFile 'putty-installer.msi'

    #- name: Install PuTTY
    #  run: |
    #    msiexec /i putty-installer.msi /qn /norestart

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: MyAppBundle
        path: "./_build" 

    - name: Copy Build Directory to EC2
      run: |
        # Replace the following placeholders with your actual values:
        $localPath = "./_build" 
        $remotePath = "C:\inetpub\wwwroot\testApp"

        # Use Robocopy to copy the directory to the EC2 instance
        robocopy $localPath "\\EC2_INSTANCE_IP\$remotePath" /e /z /mt /r:0 /w:0
        
    #- name: Copy files to AWS EC2 Windows
    #  run: |       
    #    pscp -i "C:\runner\developer-portal-ec2-key-poc.pem" -r ./_build Administrator@34.227.94.173:"C:\inetpub\wwwroot\testApp"
