name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build .NET application
      run: |
        C:\runner\nuget.exe restore # If your project uses NuGet packages
        'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe' mvc-app.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:Publish /p:PublishDir=C:\runner\published # Adjust the project path if needed

    - name: Upload to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: Administrator
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: C:\runner\published # Adjust to your build output folder
        target: C:\inetpub\wwwroot\testApp # Adjust to your app folder on EC2

    - name: SSH into EC2 and Restart IIS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: Administrator
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        script: |
          iisreset /restart
