name: Deploy build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore mvc-app.sln

    - name: Build Solution
      run: |
        msbuild.exe mvc-app.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
    
    - name: Download PuTTY Installer
      run: |
        Invoke-WebRequest -Uri 'https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.79-installer.msi' -OutFile 'putty-installer.msi'

    - name: Install PuTTY
      run: |
        msiexec /i putty-installer.msi /qn /norestart

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: MyAppBundle
        path: "./_build" 

    - name: Copy files to AWS EC2 Windows
      run: |       
        pscp -i ${ secrets.SSH_PRIVATE_KEY } -r ./_build Administrator@34.227.94.173:"C:\inetpub\wwwroot\testApp"