name: Deploy to EC2

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 7.0.402 # Use the correct version
    
    - name: Clean
      run: dotnet clean

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build .NET application
      run: |
        # Add your build commands here
          dotnet publish -c Release -o ./publish
        # Make sure your build output is in a folder, like 'publish'

    - name: Upload to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: Administrator
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: ./publish/ # Adjust to your build output folder
        target: C:\inetpub\wwwroot\testApp # Adjust to your app folder on EC2

    - name: SSH into EC2 and Restart IIS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: Administrator
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        script: |
          Restart-Service W3SVC

# Store your EC2 credentials securely in GitHub Secrets
# EC2_HOST, EC2_USER, and EC2_SSH_KEY should be added as secrets in your repository settings.