name: Deploy build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: self-hosted
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        LABEL: ec2-self-hosted-runner
        MSBUILD_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe"

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore mvc-app.sln

    - name: Build Solution
      run: |
        $env:MSBUILD_PATH mvc-app.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="./../_build"

    #- name: Upload artifact
    #  uses: actions/upload-artifact@v1.0.0
    #  with:
    #    name: MyAppBundle
    #    path: "./_build" 

    - name: Create Published directory and take backup
      run: |
        if not exist C:\runner\published (
          echo Directory does not exist
          mkdir C:\runner\published
        ) else (
           echo Directory already exists
          :: Backup the directory contents to a new directory with the current date and time
          setlocal enabledelayedexpansion
          for /f "tokens=1-9 delims=/:. " %%a in ('echo !DATE! !TIME!') do (
            set "YY=%%c"
            set "MM=%%b"
            set "DD=%%a"
            set "HH=%%d"
            set "NN=%%e"
            set "SS=%%f"
          )
          mkdir "C:\runner\backup\!YY!!MM!!DD!!HH!!NN!!SS!"
          xcopy /s /e /q C:\runner\published "C:\runner\backup\!YY!!MM!!DD!!HH!!NN!!SS!"
        )

    - name: Copy Build Directory published directory
      run: |
        # Replace the following placeholders with your actual values:
        #xcopy "C:\runner\actions-runner-win-x64-2.311.0\_work\mvc-app\_build" "C:\runner\published" /E /H /Y
        xcopy "_build" "C:\runner\published" /E /H /Y

    - name: Restart IIS
      run: |
          iisreset /restart
        
        