name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build .NET application
      run: |
        nuget restore # If your project uses NuGet packages
        msbuild /p:Configuration=Release /p:Platform="Any CPU" # Adjust the project path if needed

    - name: Upload to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: Administrator
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: ./ # Adjust to your build output folder
        target: C:\inetpub\wwwroot\testApp # Adjust to your app folder on EC2

    - name: SSH into EC2 and Restart IIS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: Administrator
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        script: |
          iisreset /restart
