name: Deploy build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: self-hosted
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        LABEL: ec2-self-hosted-runner
        #MSBUILD_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe"

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore mvc-app.sln

    - name: Build Solution
      run: |
        MSBuild.exe mvc-app.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
       
        #- name: Upload artifact
        #  uses: actions/upload-artifact@v1.0.0
        #  with:
        #    name: MyAppBundle
        #    path: "./_build" 

    - name: Create Published directory and take backup
      run: |
        if (-not (Test-Path -Path "C:\runner\published")) {
            Write-Host "Directory does not exist"
            New-Item -Path "C:\runner\published" -ItemType Directory
        } else {
            Write-Host "Directory already exists"
            # Backup the directory contents to a new directory with the current date and time
            $currentDateTime = Get-Date -Format "yyyyMMddHHmmss"
            $backupDirectory = "C:\runner\backup\$currentDateTime"
            New-Item -Path $backupDirectory -ItemType Directory
            Copy-Item -Path "C:\runner\published\*" -Destination $backupDirectory -Recurse
        }


    - name: Copy Build Directory published directory
      run: |
        # Replace the following placeholders with your actual values:
        #xcopy "C:\runner\actions-runner-win-x64-2.311.0\_work\mvc-app\_build" "C:\runner\published" /E /H /Y
        xcopy ".\_build" "C:\runner\published" /E /H /Y

    - name: Restart IIS
      run: |
          iisreset /restart
        
        