name: Deploy build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: self-hosted
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore mvc-app.sln

    - name: Build Solution
      run: |
        msbuild.exe mvc-app.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: MyAppBundle
        path: "./_build" 

    - name: Copy files to AWS EC2 Windows
      run: |
        # Replace 'your-ec2-instance-ip' with the actual IP address or DNS of your EC2 Windows instance.
        # Replace 'YourKeyPair.pem' with the private key file used for connecting to your EC2 Windows instance.
        # Replace 'C:\path\to\destination' with the path to the destination directory on your EC2 Windows instance.

        # Use PSCP (from PuTTY) to copy the files
        pscp -i "C:\runner\developer-portal-ec2-key-poc.pem" -r ./_build ec2-user@34.227.94.173:"C:\inetpub\wwwroot\testApp"

        # Use Plink (from PuTTY) to execute commands on the EC2 instance (if needed)
        # plink -i "YourKeyPair.pem" ec2-user@your-ec2-instance-ip "your-command"